### ISSUE TITLE
add a single review step to simplify the documentation on docs.sysrev.com

### ISSUE THREAD

**Issue by tomlue** [insilica/srvc-template#1]
I tried modifying pubmed search as shown below, but the sink.jsonl no longer gets populated and the label-web step doesn't display display any documents.

```
pubmed-search:
    steps:
      - uses: github:insilica/srvc-pubmed-search
        query: angry bees
      - run-embedded: remove-reviewed
      - run-embedded: label-web
        labels: [include, category]
        port: 5005
```
